[tox]
envlist = py37,py39
skipsdist = true

[testenv]
deps =
    molecule
    molecule_podman
    ansible>=2.9
commands =
    molecule test -s podman

[testenv:py37]
basepython = python3.7

[testenv:py39]
basepython = python3.9
